[software]
# Gaussian Splatting repository path.
gaussian_splatting_root_dir = D:\gaussian-splatting\
# Depth-Anything-V2 repository path.
depth_anything_root_dir = D:\Depth-Anything-V2\

[data]
root_dir = D:\path\to\data
# video_path can either be a file path or a directory containing the video(s) (mpeg, mpg, or mp4)
; video_path = D:\path\to\data\file.mpg
; frames_dir = D:\path\to\data\input
; images_dir = D:\path\to\data\images
; sparse_dir = D:\path\to\data\sparse\0
; depths_dir = D:\path\to\data\depths
; splats_dir = D:\path\to\data\splats

# Tasks can define a 'force' and/or 'skip' option.
# The 'force' option starts the task even if its output exists.
# The 'skip' option stops the task, even if its output does not exist.
# The 'skip' option takes precedence to the 'force' option.

[slice]
fps = 5.0
; force = true
; skip = true

[sfm]
; resize = true
; force = true
; skip = true

[depths]
enable = true
; force = true
; skip = true

[splats]
train_exposure = true
; force = true